//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAssist.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TurnTracker {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TurnTracker() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VAssist.Resources.TurnTracker", typeof(TurnTracker).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Tracker.
        /// </summary>
        internal static string AuthorName {
            get {
                return ResourceManager.GetString("AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn available, reaction unavailable..
        /// </summary>
        internal static string BlueDescription {
            get {
                return ResourceManager.GetString("BlueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Available Reaction(s).
        /// </summary>
        internal static string ButtonReactionCycleLabel {
            get {
                return ResourceManager.GetString("ButtonReactionCycleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Max Reactions.
        /// </summary>
        internal static string ButtonReactionMaxLabel {
            get {
                return ResourceManager.GetString("ButtonReactionMaxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Turn.
        /// </summary>
        internal static string ButtonToggleTurnLabel {
            get {
                return ResourceManager.GetString("ButtonToggleTurnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director, select characters..
        /// </summary>
        internal static string CharacterSelectionPlaceholder {
            get {
                return ResourceManager.GetString("CharacterSelectionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Controller.
        /// </summary>
        internal static string ControllerFieldName {
            get {
                return ResourceManager.GetString("ControllerFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Assigned.
        /// </summary>
        internal static string ControllerFieldValueDefault {
            get {
                return ResourceManager.GetString("ControllerFieldValueDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director Controlled Characters.
        /// </summary>
        internal static string DirectorCharactersFieldName {
            get {
                return ResourceManager.GetString("DirectorCharactersFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None Selected.
        /// </summary>
        internal static string DirectorCharactersFieldValueDefault {
            get {
                return ResourceManager.GetString("DirectorCharactersFieldValueDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director.
        /// </summary>
        internal static string DirectorFieldName {
            get {
                return ResourceManager.GetString("DirectorFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn, reaction available..
        /// </summary>
        internal static string GreenDescription {
            get {
                return ResourceManager.GetString("GreenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string KeyFieldName {
            get {
                return ResourceManager.GetString("KeyFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Team.
        /// </summary>
        internal static string LeaveTeamOptionLabel {
            get {
                return ResourceManager.GetString("LeaveTeamOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Player Character Name:.
        /// </summary>
        internal static string NewNPCModalComponentLabel {
            get {
                return ResourceManager.GetString("NewNPCModalComponentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name....
        /// </summary>
        internal static string NewNPCModalComponentPlaceholder {
            get {
                return ResourceManager.GetString("NewNPCModalComponentPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Non-Player Characters.
        /// </summary>
        internal static string NewNPCModalTitle {
            get {
                return ResourceManager.GetString("NewNPCModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn unavailable, reaction available..
        /// </summary>
        internal static string OrangeDescription {
            get {
                return ResourceManager.GetString("OrangeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn, reaction unavailable..
        /// </summary>
        internal static string RedDescription {
            get {
                return ResourceManager.GetString("RedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation History.
        /// </summary>
        internal static string RotationFieldNamePrefix {
            get {
                return ResourceManager.GetString("RotationFieldNamePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Turn.
        /// </summary>
        internal static string RotationFieldValueDefault {
            get {
                return ResourceManager.GetString("RotationFieldValueDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string TeamFieldValueDefault {
            get {
                return ResourceManager.GetString("TeamFieldValueDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players, join a team. Director, add characters to a team..
        /// </summary>
        internal static string TeamSelectionPlaceholder {
            get {
                return ResourceManager.GetString("TeamSelectionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTS v0.1.
        /// </summary>
        internal static string TurnTrackerCurrentVersion {
            get {
                return ResourceManager.GetString("TurnTrackerCurrentVersion", resourceCulture);
            }
        }
    }
}
